# Generated by Django 4.2.7 on 2024-01-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
