# Generated by Django 4.2.7 on 2024-03-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_producto_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="subcategoria",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
