# Generated by Django 4.2.7 on 2024-03-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_usuario_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snack",
            name="categoria_snack",
        ),
        migrations.RemoveField(
            model_name="snack",
            name="producto_ptr",
        ),
        migrations.RemoveField(
            model_name="vitamina",
            name="categoria_vitamina",
        ),
        migrations.RemoveField(
            model_name="vitamina",
            name="producto_ptr",
        ),
        migrations.DeleteModel(
            name="Proteina",
        ),
        migrations.DeleteModel(
            name="Snack",
        ),
        migrations.DeleteModel(
            name="Vitamina",
        ),
    ]
